
name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时检查一次
  workflow_dispatch:       # 支持手动触发

permissions:
  contents: write         # 必需推送权限

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      # - name: 配置Git身份
      #   run: | 
      #     git config user.name "Sync Bot"
      #     git config user.email "actions@users.noreply.github.com"

      - name: 添加上游仓库
        run: |
          git remote add upstream https://github.com/78/xiaozhi-esp32.git
          git fetch upstream

      - name: 合并更新
        run: |
          git checkout main
          git merge --no-edit upstream/main
          git push origin main
